const lists = {};
lists.tags = [
    { value: 'is_beverage', text: 'Beverage' },
    { value: 'burger', text: 'Burger' },
    { value: 'canadian', text: 'Canadian' },
    { value: 'caribbean', text: 'Caribbean' },
    { value: 'cheap', text: 'Cheap' },
    { value: 'chinese', text: 'Chinese' },
    { value: 'dessert', text: 'Dessert' },
    { value: 'fast_food', text: 'Fast Food' },
    { value: 'fine_food', text: 'Fine Food' },
    { value: 'gluten_free', text: 'Gluten Free' },
    { value: 'greek', text: 'Greek' },
    { value: 'halal', text: 'Halal' },
    { value: 'has_eggs', text: 'Has Eggs' },
    { value: 'has_peanuts', text: 'Has Peanuts' },
    { value: 'has_soybeans', text: 'Has Soybeans' },
    { value: 'has_treenuts', text: 'Has Treenuts' },
    { value: 'has_wheat', text: 'Has Wheat' },
    { value: 'healthy', text: 'Healthy' },
    { value: 'indian', text: 'Indian' },
    { value: 'italian', text: 'Italian' },
    { value: 'jain', text: 'Jain' },
    { value: 'japanese', text: 'Japanese' },
    { value: 'korean', text: 'Korean' },
    { value: 'kosher', text: 'Kosher' },
    { value: 'lactose_free', text: 'Lactose Free' },
    { value: 'mexican', text: 'Mexican' },
    { value: 'middle_eastern', text: 'Middle Eastern' },
    { value: 'pizza', text: 'Pizza' },
    { value: 'snack', text: 'Snack' },
    { value: 'spicy', text: 'Spicy' },
    { value: 'sushi', text: 'Sushi' },
    { value: 'thai', text: 'Thai' },
    { value: 'vegan', text: 'Vegan' },
    { value: 'vegetarian', text: 'Vegetarian' },
    { value: 'vietnamese', text: 'Vietnamese' }
];

lists.meat = [
    { value: 'bacon', text: 'Bacon' },
    { value: 'bear', text: 'Bear' },
    { value: 'beef', text: 'Beef' },
    { value: 'buffalo', text: 'Buffalo' },
    { value: 'calf', text: 'Calf' },
    { value: 'caribou', text: 'Caribou' },
    { value: 'chicken', text: 'Chicken' },
    { value: 'duck', text: 'Duck' },
    { value: 'goat', text: 'Goat' },
    { value: 'goose', text: 'Goose' },
    { value: 'ham', text: 'Ham' },
    { value: 'hen', text: 'Hen' },
    { value: 'horse', text: 'Horse' },
    { value: 'kangaroo', text: 'Kangaroo' },
    { value: 'lamb', text: 'Lamb' },
    { value: 'moose', text: 'Moose' },
    { value: 'mutton', text: 'Mutton' },
    { value: 'opossum', text: 'Opossum' },
    { value: 'ostrich', text: 'Ostrich' },
    { value: 'pork', text: 'Pork' },
    { value: 'quail', text: 'Quail' },
    { value: 'rabbit', text: 'Rabbit' },
    { value: 'snake', text: 'Snake' },
    { value: 'squirrel', text: 'Squirrel' },
    { value: 'turkey', text: 'Turkey' },
    { value: 'turtle', text: 'Turtle' },
    { value: 'veal', text: 'Veal' }
];

lists.seafood = [
    { value: 'alaska_pollack', text: 'Alaska Pollack' },
    { value: 'catfish', text: 'Catfish' },
    { value: 'clam', text: 'Clam' },
    { value: 'cod', text: 'Cod' },
    { value: 'crab', text: 'Crab' },
    { value: 'eel', text: 'Eel' },
    { value: 'lobster', text: 'Lobster' },
    { value: 'pangasius', text: 'Pangasius' },
    { value: 'pike', text: 'Pike' },
    { value: 'salmon', text: 'Salmon' },
    { value: 'shark', text: 'Shark' },
    { value: 'shrimp', text: 'Shrimp' },
    { value: 'tilapia', text: 'Tilapia' },
    { value: 'trout', text: 'Trout' },
    { value: 'tuna', text: 'Tuna' }
];

export default lists;