export const SHOW_PREFERENCE_OVERLAY = 'SHOW_PREFERENCE_OVERLAY';
export const CLOSE_PREFERENCE_OVERLAY = 'CLOSE_PREFERENCE_OVERLAY';

export const SHOW_FOOD_ITEM_OVERLAY = 'SHOW_FOOD_ITEM_OVERLAY';
export const CLOSE_FOOD_ITEM_OVERLAY = 'CLOSE_FOOD_ITEM_OVERLAY';

export const SHOW_SIGN_IN_OVERLAY = 'SHOW_SIGN_IN_OVERLAY';
export const CLOSE_SIGN_IN_OVERLAY = 'CLOSE_SIGN_IN_OVERLAY';

export const CHANGE_DRAWER_ITEM = 'CHANGE_DRAWER_ITEM';