export const SHOW_PREFERENCE_OVERLAY = 'SHOW_PREFERENCE_OVERLAY';
export const CLOSE_PREFERENCE_OVERLAY = 'CLOSE_PREFERENCE_OVERLAY';

export const SHOW_FOOD_ITEM_OVERLAY = 'SHOW_FOOD_ITEM_OVERLAY';
export const CLOSE_FOOD_ITEM_OVERLAY = 'CLOSE_FOOD_ITEM_OVERLAY';